config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  devise_for :users

  resources :profiles do
    get 'search', on: :collection
    put :favorite, on: :member
    resources :comments
  end
  resources :companies
  resources :skills
  resources :joblevels
  resources :benefits
  resources :jobs do
    get 'search', on: :collection
    resources :profilejobs do
      get 'search', on: :collection
    end
  end
 
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :companies, only: %i[show index create update destroy]
    end
  end
  
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
    belongs_to :joblevel
    belongs_to :skill
    has_many :comments, dependent: :destroy
    has_one_attached :avatar

    has_many :profilejobs, :dependent => :destroy
    has_many :jobs, :through => :profilejobs

    has_many :favorite_profiles
    has_many :favorited_by, through: :favorite_profiles, source: :user


    validates :name, :address, :cellphone, :date_birth, presence: {message: '...deve ser informado'}
    validates :name, length: { minimum: 5, message: '....deve ter tamanho minimo de 5 caracter'}

    enum languages: { "basic English": 0, "intermediary English": 15, "Advanced English": 30}
    def set_default_languages
        self.languages ||= :"basic English"
    end
   
    enum education_level: { "high school": 0, "technical": 15, "graduate": 30}
    def set_default_education_level
        self.education_level ||= :"graduate"
    end

    enum education_status: { "studying": 0, "braided": 15, "concluded": 30}
    def set_default_education_status
        self.education_status ||= :"studying"
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    before_action :set_find, only: [:show, :edit, :update, :destroy, :favorite]
    before_action :authenticate_user!
       

    def index
      @profiles = Profile.all
      @jobs = Job.all
    end
    
    def new
      @profile = Profile.new
      @skills = Skill.all
      @joblevels = Joblevel.all
      @users = User.all
      @jobs = Job.all
    end
    
    def show
      @comments = Comment.all
      @skills  = Skill.all
      @joblevels = Joblevel.all
      @users = User.all
    end

    def edit
      @skills  = Skill.all
      @joblevels = Joblevel.all
      @users = User.all
      
    end


    def create
      @profile = Profile.new(profile_params)
      @profile.email = current_user.email
      @jobs = Job.all
      if @profile.save
        current_user.andamento!
        flash[:notice] = 'Perfil concluido com sucesso'
        redirect_to @profile
        ProfilesMailer.welcome(@profile.id)        
      else
        @skills = Skill.all
        @joblevels = Joblevel.all
        @users = User.all
        flash[:alert] = 'Erro profiles'
        render :new
      end
    end
    
    def update
      @profile = Profile.find(params[:id])
      if @profile.update(profile_params)
        redirect_to @profile
      else
        @skills = Skill.all
        @joblevels = Joblevel.all
        @users = User.all
        render :edit
      end
    end

    def destroy
      @profile.destroy
      redirect_to @profile, notice: 'Perfil excluido com sucesso'
    end

    def search
       @profiles = Profile.where("education_course LIKE ? OR experience_reponsibility LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
    end

    def favorite
      type = params[:type]
        if type == "favorite"
          current_user.favorites << @profile
          redirect_back fallback_location: root_path, notice: "Voce favoritou #{@profile.name}"
        elsif type == "unfavorite"
          current_user.favorites.delete(@profile)
          redirect_back fallback_location: root_path, notice: "Desfavoritado #{@profile.name}"
        else
          redirect_back fallback_location: root_path, notice: "Nada modificado"
        end
    end

  private

    def profile_params
      params.require(:profile).permit(:name, :email, :social_name, :joblevel_id, :skill_id, 
                                      :user_id, :languages, :address, :cellphone,
                                      :date_birth, :languages, :education_level,
                                      :education_status, :education_institution,
                                      :education_course, :education_end_date,
                                      :experience_company, :experience_reponsibility,
                                      :experience_role, :experience_start_date,
                                      :experience_end_date,:experience_current_position, :avatar, :job_id)
    end

    def set_find
         @profile = Profile.find(params[:id])
    end

end

app/views/profiles/_form.html.erb
<div class="jumbotron">

  <% if @profile.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <% @profile.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>


  <%= form_for(profile) do |f| %>
    
      <%= f.label :avatar, "Foto" %><br>
      <%= f.file_field :avatar %>
    <br>
    <br>

      <%= f.label :user_id, 'Tipo de Perfil' %>	
      <%= f.collection_select(:user_id, @users, :id, :role) %>		   
   
      Email: <%= f.label :email, current_user.email %><br>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :social_name %>
      <%= f.text_field :social_name %>
      <%= f.label :date_birth %>
      <%= f.date_select :date_birth, start_year: Date.today.year - 100 %>
      <%= f.label :cellphone %>
      <%= f.text_field :cellphone %>
      <%= f.label :address %>
      <%= f.text_field :address %>
    <br>
    <br>
      <%= f.label :languages %>
      <%= f.select(:languages, Profile.languages.keys.map {|language| [language.titleize,language]}) %>
    <br>
    <br>
      <%= f.label :education_institution %>
      <%= f.text_field :education_institution %>
      <%= f.label :education_course %>
      <%= f.text_field :education_course %>
      <%= f.label :education_level %>
      <%= f.select(:education_level, Profile.education_levels.keys.map {|education_level| [education_level.titleize,education_level]}) %>
      <%= f.label :education_status %>
      <%= f.select(:education_status, Profile.education_statuses.keys.map {|education_status| [education_status.titleize,education_status]}) %>
      <%= f.label :education_end_date %>
      <%= f.date_select :education_end_date, start_year: Date.today.year - 100 %>
    <br>
    <br>
      <%= f.label :experience_company %>
      <%= f.text_field :experience_company %>
      <%= f.label :experience_reponsibility %>
      <%= f.text_field :experience_reponsibility %>
      <%= f.label :experience_role %>
      <%= f.text_field :experience_role %>
      <%= f.label :joblevel_id %>
      <%= f.collection_select(:joblevel_id, @joblevels, :id, :name) %>
      <%= f.label :skill_id %>
      <%= f.collection_select(:skill_id, @skills, :id, :name) %>
    <br>
    <br>
      <%= f.label :experience_start_date %>
      <%= f.date_select :experience_start_date, start_year: Date.today.year - 100 %>
      <%= f.label :experience_end_date %>
      <%= f.date_select :experience_end_date, start_year: Date.today.year - 100 %>
      <%= f.label :experience_current_position %>
      <%= f.check_box :experience_current_position, checked: @profile.new_record? %>
    <br>
    <br>
      <%= f.submit class:'btn btn-primary' %>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<p>Editar Perfil</p>
<%= render partial: "form", locals: {profile: @profile} %>

<br><br><br>   

<% if current_user.candidate?%>
      <%= link_to 'Deletar', profile_path(@profile), method: :delete, data: { confirm: "Confirma exclusão do perfil: #{@profile.name}?" } %>
<% end %>

<%= link_to 'Voltar', profiles_path %>

app/views/profiles/index.html.erb
<p>Perfil Candidato</p>
<br>
<br>
<% if user_signed_in? %> 

    Olá <%= current_user.email %>
    <br>
    <br>
    <br>
    <%= form_with url: search_profiles_path, local: true, method: :get do %>
        <%= label_tag(:q, 'Pesquisar Canditato') %>
        <%= text_field_tag(:q) %>
        <%= submit_tag 'Buscar' %>
    <% end %>
    
    <% if @profiles.empty? %>
        Não existem perfis cadastrados
    <% end %>
   <br>
    <% @profiles.each do |profile| %>
        <%= link_to profile.name, profile_path(profile) %><br>
    <% end %>

<% end %>
<br>
<br>
<%= link_to 'Voltar', root_path %>

app/views/profiles/new.html.erb
<p>Novo Perfil</p>
<%= render partial: "form", locals: {profile: @profile} %>

<br><br><br>   
<%= link_to 'Voltar', profiles_path %>

app/views/profiles/search.html.erb
<div class="jumbotron">
    <p>Pesquisando Candidatos</p>

    Olá <%= current_user.email %><br>
        <%= form_with url: search_profiles_path, local: true, method: :get do %>
        <%= label_tag(:q, 'Pesquisar Canditato') %>
        <%= text_field_tag(:q) %>
        <%= submit_tag 'Buscar' %>
        <% end %>

    <% if @profiles.empty? %>
        Não existem candidados para pesquisa solicitada
    <% end %>

    <% @profiles.each do |profile| %>
        <%= link_to profile.name, profile_path(profile) %><br>
    <% end %>
    <br>
    <br>
    <%= link_to 'Voltar', profiles_path %>
</div>

app/views/profiles/show.html.erb
<p>Perfil Candidato</p>
<br>
<p>Email: <%= current_user.email %></p>
<p>Nome: <%= @profile.name %></p>
<p>Nome Social:<%= @profile.social_name %></p>
<p>Endereço: <%= @profile.address %></p>
<p>Celular:<%= @profile.cellphone %></p>
<p>Data Nascimento <%= l(@profile.date_birth) %></p>
<p>Idiomas:<%= @profile.languages %></p>
<p>Instituição de Ensino: <%= @profile.education_institution%></p>
<p>Nivel Educacional:<%= @profile.education_level %></p>
<p>Status do Curso: <%= @profile.education_status %></p>
<p>Curso: <%= @profile.education_course %></p>
<p>Data Conclusão: <%= l(@profile.education_end_date) %></p>
<p>Experiencia Profissional: <%= @profile.experience_company %></p>
<p>Responsabilidades: <%= @profile.experience_reponsibility %></p>
<p>Cargo: <%= @profile.experience_role%></p>
<p>Nivel do Cargo: <%= @profile.joblevel.name %></p>
<p>Habilidades: <%= @profile.skill.name %></p>
<p>Data inicio: <%= l(@profile.experience_start_date) %></p>

<% if @profile.experience_current_position? %>
    <p>Atual Emprego </p>
<% else %>
    <p>Data inicio: <%= l(@profile.experience_end_date) %></p>
<% end %>

<% if current_user.headhunter? %>
    <% if current_user %>
        <%= link_to "favorite", favorite_profile_path(@profile, type: "favorite"), method: :put %>
        <%= link_to "unfavorite", favorite_profile_path(@profile, type: "unfavorite"), method: :put %>
    <% end %>
<% end %>


<p><%= image_tag(@profile.avatar) if @profile.avatar.attached? %></p>

<%= link_to 'Voltar', root_path %>
<%= link_to 'Novo Comentario', new_profile_comment_path(@profile) %>
<%= link_to pluralize(@profile.comments.size, 'Comentário', 'Comentários'), profile_comments_path(@profile) %>


<% if current_user.candidate?%>
    <%= link_to 'Editar Perfil', edit_profile_path(@profile) %>
    <%= link_to 'Deletar', profile_path(@profile), method: :delete, data: { confirm: "Confirma exclusão do perfil: #{@profile.name}?" } %>
<% end %>