config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  devise_for :users

  resources :profiles do
    get 'search', on: :collection
    put :favorite, on: :member
    resources :comments
  end
  resources :companies
  resources :skills
  resources :joblevels
  resources :benefits
  resources :jobs do
    get 'search', on: :collection
    resources :profilejobs do
      get 'search', on: :collection
    end
  end
 
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :companies, only: %i[show index create update destroy]
    end
  end
  
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :company
    belongs_to :benefit
    belongs_to :skill
    belongs_to :joblevel
    belongs_to :user

    has_many :profilejobs, :dependent => :destroy
    has_many :profiles, :through => :profilejobs
    

    validates :title, :description, :workplace, :end_date, :salary_range, :status, presence: {message: '...deve ser informado'}
    
    enum salary_range: { "1000_to_3000": 0, "3001_to_5000": 15, "5001_to_8000": 30}

    def set_default_salary_range
        self.salary_range ||= :"1000_to_3000"
    end

    enum status: { "active": 0, "disabled": 15}

    def set_default_status
        self.status ||= :"active"
    end
    
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :set_find, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


    def index
      @jobs = Job.all
      @users = User.all
      @profiles = Profile.all
    end
    
    def new
      @job = Job.new
      @skills  = Skill.all
      @joblevels = Joblevel.all
      @companies = Company.all
      @benefits = Benefit.all
      @users = User.all
      @profiles = Profile.all
    end
    
    def show
      @skills  = Skill.all
      @joblevels = Joblevel.all
      @companies = Company.all
      @benefits = Benefit.all
      @users = User.all
    end

    def edit
      @jobs = Job.all
      @skills  = Skill.all
      @joblevels = Joblevel.all
      @companies = Company.all
      @benefits = Benefit.all
      @users = User.all
    end
    
    def create
      @job = Job.new(job_params)
      @job.email = current_user.email
      @job.user_id = current_user.id
      @profiles = Profile.all
        if @job.save
          flash[:notice] = 'Vaga criada com sucesso.'
          redirect_to @job
        else
          @skills = Skill.all
          @joblevels = Joblevel.all
          @companies = Company.all
          @benefits = Benefit.all
          @users = User.all
          flash[:alert] = 'Erro jobs'
          render :new
        end
    end
    
    def update
      @job = Job.find(params[:id])

      if @job.update(job_params)
        redirect_to @job
      else
     
        render :edit
      end
    end

    def destroy
      @job.destroy
      redirect_to @job, notice: "Vaga excluida com sucesso"
    end

    def search
        @jobs = Job.where('title like ? OR description like ?', "%#{params[:q]}%", "%#{params[:q]}%")
    end


private

  def job_params
    params.require(:job).permit(:title, :description, :end_date, 
                                :workplace, :salary_range, :company_id, 
                                :benefit_id, :joblevel_id, :skill_id, :user_id, :email, :status)
  end

  def set_find
    @job = Job.find(params[:id])
  end


end
  

app/views/jobs/_form.html.erb
<% if @job.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @job.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>



<%= form_for(job) do |f| %>
  
       Criado por: <%= f.label :email, current_user.email %>
    <% f.label :user_id, current_user.id %><br>
  
  
  
    <%= f.label :title %>
    <%= f.text_field :title %><br>
  
  
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  
  
    <%= f.label :workplace %>
    <%= f.text_field :workplace %><br>
  
  
    <%= f.label :end_date %> 
    <%= f.text_field :end_date %><br>
  
  
    <%= f.label :salary_range %>
    <%= f.select(:salary_range, Job.salary_ranges.keys.map {|salary| [salary.titleize,salary]}) %><br>
  
  
    <%= f.label :skill_id %>
    <%= f.collection_select(:skill_id, @skills, :id, :name) %><br>
  
   
    <%= f.label :company_id %>
    <%= f.collection_select(:company_id, @companies, :id, :name) %><br>
  
  
    <%= f.label :joblevel_id %>
    <%= f.collection_select(:joblevel_id, @joblevels, :id, :name) %><br>
  
  
    <%= f.label :benefit_id %>
    <%= f.collection_select(:benefit_id, @benefits, :id, :name) %><br>
  
  
    <%= f.label :status %>
    <%= f.select(:status, Job.statuses.keys.map {|status| [status.titleize,status]}) %><br>
  

     <%= f.submit class:'btn btn-primary' %>
  
<% end %>

app/views/jobs/edit.html.erb
<p>Editar Vaga</p>

<%= render partial: "form", locals: {job: @job} %>

<br><br>   
<%= link_to 'Voltar', jobs_path %>

app/views/jobs/index.html.erb
<p>Vagas</p>
<br>
<br>

<% if user_signed_in? %> 
  
    Olá <%= current_user.email %> <br><br>
    
    <%= form_with url: search_jobs_path, local: true, method: :get do %>
        <%= label_tag(:q, 'Pesquisar Vaga') %>
        <%= text_field_tag(:q) %>
        <%= submit_tag 'Buscar' %>
    <% end %>
    <br>
    <br>
    <% if current_user.headhunter? %>
        <%= link_to "Nova vaga", new_job_path %> <br><br>
    
            <% if @jobs.empty? %>
                <p> Não existem vagas cadastradas</p>
            <% end %>
            
            <% @jobs.each do |job| %>
                <% if job.user_id == current_user.id %>
                    <%= link_to job.title, job_path(job) %> Status Vaga: <%= job.status %>
                <% end %>
            <% end %>
   
    <% end %>

    <% if current_user.candidate? %>

         <% if @jobs.empty? %>
            <p> Não existem vagas cadastradas </p>
        <% end %>
        
        <% @jobs.each do |job| %>
            <% if job.status == 'active' %>
                <%= link_to job.title, job_path(job) %><br>
            <%end %>
        <% end %>

    <% end %>

<% end %>
<br>
<br>   
<%= link_to 'Voltar', root_path %>

app/views/jobs/new.html.erb
    <p>Nova Vaga</p>
    <%= render partial: "form", locals: {job: @job} %>

    <br><br><br>   
    <%= link_to 'Voltar', jobs_path %>

app/views/jobs/search.html.erb
<div class="jumbotron">
    <p>Pesquisando Vagas</p><br><br>
    <% if user_signed_in? %> 
     
        <%= form_with url: search_jobs_path, local: true, method: :get do %>
            <p>
            <%= label_tag(:q, 'Pesquisar Vaga') %>
            <%= text_field_tag(:q) %>
            <%= submit_tag 'Buscar' %>
            </p>
        <% end %><br><br>

        <% if current_user.headhunter? %>
            <%= link_to "Nova vaga", new_job_path %><br><br>
            <% if @jobs.empty? %>
                 <p> Não existem vagas cadastradas</p>
            <% end %>
            <% @jobs.each do |job| %>
                <%= link_to job.title, job_path(job) %> Status Vaga: <%= job.status %>
            <% end %>
    
        <% end %>
        
        <% if current_user.candidate? %>
            <% if @jobs.empty? %>
                <p> Não existem vagas cadastradas </p>
            <% end %>
            
            <% @jobs.each do |job| %>
                <% if job.status == 'active' %>
                   <p><%= link_to job.title, job_path(job) %></p> <br>
                <%end %>
            <% end %>
        <% end %>

    <% end %>

    <p><%= link_to 'Voltar', jobs_path %><p>
</div>

app/views/jobs/show.html.erb
<div class="jumbotron">
    <% if user_signed_in? %> 
        <p>Vaga</p> 
        Titulo: <%= @job.title %> <br>
        Descrição: <%= @job.description %><br>
        Local de trabalho: <%= @job.workplace %><br>
        Encerra: <%= @job.end_date %><br>
        Faixa salarial: <%= @job.salary_range %><br>
        Habilidades: <%= @job.skill.name %><br>
        Empresa: <%= @job.company.name %><br>
        Nivel Vaga: <%= @job.joblevel.name %><br>
        Beneficio: <%= @job.benefit.name %><br>
        Criado por: <%= current_user.email %><br>
        Status Vaga: <%= @job.status %><br>

        <% if current_user.headhunter? %>
            <%= link_to 'Editar', edit_job_path(@job) %>
            <%= link_to 'Deletar', job_path(@job), method: :delete, data: { confirm: "Confirma exclusão da vaga: #{@job.title}?" } %>
            
        <% else %>
                <%= link_to 'Aplicar Vaga' , new_job_profilejob_path(@job) %>
        <% end %>
    
    <%= link_to 'Voltar', jobs_path %>

    <% end %>
    
</div>