config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  devise_for :users

  resources :profiles do
    get 'search', on: :collection
    put :favorite, on: :member
    resources :comments
  end
  resources :companies
  resources :skills
  resources :joblevels
  resources :benefits
  resources :jobs do
    get 'search', on: :collection
    resources :profilejobs do
      get 'search', on: :collection
    end
  end
 
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :companies, only: %i[show index create update destroy]
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @profiles = Profile.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <ul class="nav flex-column">
        <% if user_signed_in? %> 
            <% if current_user.headhunter? %>
                <li><%= link_to "Vagas", jobs_path %></li>
                <li><%= link_to "Empresas", companies_path %></li>
                <li><%= link_to "Habilidades", skills_path %></li>
                <li><%= link_to "Nivel Vaga", joblevels_path %></li>
                <li><%= link_to "Beneficios", benefits_path %></li>
                <li><%= link_to "Candidatos das Vagas",  search_job_profilejobs_path(:job_id) %></li><br><br>
                <li><%= link_to "Pesquisar Candidato", profiles_path %></li><br><br>
            <% else  current_user.candidate? %>
                <li><%= link_to "Vagas", search_jobs_path %></li>
                    <% if current_user.andamento? %>
                        <li><%= link_to "Minhas Vagas",  search_job_profilejobs_path(:job_id) %></li>
                        <li><%= link_to "Editar Conta", edit_user_registration_path %></li>
                        <li><%= link_to 'Completar Perfil', edit_profile_path(current_user) %></li><br>
                    <% end %>
            <% end %>

            <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
                        
            <% if current_user.novoperfil?%>
                <li><%= link_to "Novo Perfil", new_profile_path %></li><br>
            <% end %>

        <% else %>
            <li class="nav-item"><%= link_to 'Entrar', new_user_session_path %></li><br>
            <li><%= link_to "Registrar conta", new_user_registration_path %><br></li>   
        <% end %>
    </ul>