config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  devise_for :users

  resources :profiles do
    get 'search', on: :collection
    put :favorite, on: :member
    resources :comments
  end
  resources :companies
  resources :skills
  resources :joblevels
  resources :benefits
  resources :jobs do
    get 'search', on: :collection
    resources :profilejobs do
      get 'search', on: :collection
    end
  end
 
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :companies, only: %i[show index create update destroy]
    end
  end
  
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :jobs

    validates :name, :cnpj, :address, :description,  presence: {message: '...deve ser informado'}
    validates :name, :cnpj, uniqueness: {message: '...já está em uso'}
    validates :description, length: { minimum: 20, message: '....deve ter tamanho minimo de 20 caracter'}
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::V1::ApiController
    def show
        @company = Company.find(params[:id])
        render json: @company
    end

    def index
        @companies = Company.all
        render json: @companies
    end

    def create
        @company = Company.new(params.permit(%i[name address cnpj description]))
        if @company.valid?
           @company.save!
           render json: @company, status: 201
        else 
           render json: 'error', status: 412 
        end
    end

    def update
        @company = Company.find(params[:id])
        if @company.update(params.permit(%i[name address cnpj description]))
          render json: @company, status: 200
        else 
          render json: 'error', status: 412 
        end
    end

    def destroy
        @company = Company.find(params[:id])
        if @company.destroy
          render json: {message: "Company delete with Successfully."}, status: 200
        end
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    before_action :set_find, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :authorize_headhunter

    def index
      @companies = Company.all
    end
    
    def new
      @company = Company.new
    end
    
    def show
    end

    def edit
      @companies = Company.all
    end


    def create
      @company = Company.new(company_params)
      if @company.save
        flash[:notice] = 'Empresa criada com sucesso.'
        redirect_to @company
      else
        flash[:alert] = 'Erro'
        render :new
      end
    end
    
    def update
      @company = Company.find(params[:id])
      if @company.update(company_params)
        redirect_to @company
      else
        
        render :edit
      end
    end

    def destroy
      @company.destroy
      redirect_to @company, notice: "Empresa excluida com sucesso"
    end


  private

    def company_params
      params.require(:company).permit(:name,:cnpj,:address,:description)
    end

    def set_find
      @company = Company.find(params[:id])
    end


end
  

app/views/companies/_form.html.erb
<% if @company.errors.any? %>
 <div class="alert alert-danger" role="alert">
  <% @company.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
</div>
<% end %>



<%= form_for(company) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
  </p>
   <p>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %><br>
  </p>
   <p>
    <%= f.label :address %>
    <%= f.text_field :address %><br>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
  </p>
  <p>
     <%= f.submit class:'btn btn-primary' %>
  </p>
<% end %>

app/views/companies/edit.html.erb
<p>Editando empresa<p>
<%= render partial: "form", locals: {company: @company} %>

<br><br><br>   
<%= link_to 'Voltar', companies_path %>

app/views/companies/index.html.erb
<p>Empresas</p>

<%= link_to "Nova empresa", new_company_path %> <br><br>

<% if @companies.empty? %>
    <p> Não existem empresas cadastradas</p>
<% end %>

<% @companies.each do |company| %>
    <%= link_to company.name, company_path(company)%>
    <%= link_to company.cnpj, company_path(company)%><br>
<% end %>
<br><br><br>    
<%= link_to 'Voltar', root_path %>

app/views/companies/new.html.erb
<p>Nova empresa</p>
<%= render partial: "form", locals: {company: @company} %>

<br><br><br>   
<%= link_to 'Voltar', companies_path %>

app/views/companies/show.html.erb
<p>Empresa </p>

<p>Nome: <%= @company.name %></p>
<p>CNPJ: <%= @company.cnpj %></p>
<p>Endereço: <%= @company.address %></p>
<p>Descrição: <%= @company.description %></p>

<%= link_to 'Voltar', companies_path %>
<%= link_to 'Editar', edit_company_path(@company) %>
<%= link_to 'Deletar', company_path(@company), method: :delete, data: { confirm: "Confirma exclusão da empresa: #{@company.name}?" } %>